language: c

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script:
  - "shellcheck scripts/*"
  - "./dev prod &"
  - "./dev ci"
